# Generated by Django 3.0.8 on 2020-09-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Acerca de',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta'},
        ),
        migrations.AddField(
            model_name='question',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Category'),
        ),
    ]
