# Generated by Django 3.0.8 on 2020-09-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20200922_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='text',
        ),
    ]
