# Generated by Django 3.1.5 on 2021-01-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210120_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generator.select'),
        ),
    ]
