# Generated by Django 3.1.5 on 2021-01-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20210120_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='select',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
