# Generated by Django 3.1.5 on 2021-01-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_select_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='order',
        ),
    ]
