# Generated by Django 3.1.5 on 2021-01-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_remove_select_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
