# Generated by Django 3.1.5 on 2021-01-22 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20210121_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.select'),
        ),
    ]
