# Generated by Django 3.1.5 on 2021-01-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_auto_20210121_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
