# Generated by Django 3.1.5 on 2021-01-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_auto_20210122_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categories',
        ),
        migrations.AddField(
            model_name='select',
            name='categories',
            field=models.ManyToManyField(to='generator.Question'),
        ),
    ]
