# Generated by Django 3.1.5 on 2021-01-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_auto_20210122_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='select',
            name='questions',
        ),
        migrations.AlterField(
            model_name='select',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
