# Generated by Django 3.1.5 on 2021-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='select',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='orden'),
        ),
    ]
