# Generated by Django 3.1.5 on 2021-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_question_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.CharField(default='Buenos días!', max_length=200)),
                ('afternoon', models.CharField(default='Buenas tardes!', max_length=200)),
                ('night', models.CharField(default='Buenas noches!', max_length=200)),
                ('by', models.CharField(default='Saludos!', max_length=200)),
            ],
            options={
                'verbose_name': 'Saludo',
            },
        ),
    ]
